version: '3.8'
services:
  postgres-14:
    image: postgres:14.1
    ports:
      - "5434:5434"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
    environment:
      POSTGRES_PASSWORD: 4oXFFR2Gwjex
      POSTGRES_DB: promotion_analysis
  postal-tracking:
    depends_on:
      postgres-14:
        condition: service_healthy
    build: ./
    ports:
      - "8084:8084"
    environment:
      server.port: 8084
      spring.datasource.url: jdbc:postgresql://postgres-14/promotion_analysis
      spring.datasource.username: postgres
      spring.datasource.password: 4oXFFR2Gwjex
