--liquibase formatted sql

--changeset vasiliy.sharpf:1
CREATE SCHEMA IF NOT EXISTS promo;

--changeset vasiliy.sharpf:2
CREATE TABLE promo.chains
(
    id       int           NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- surrogate ID
    name     varchar(512)  NOT NULL                                               -- Chain_name
);

--changeset vasiliy.sharpf:3
CREATE TABLE promo.categories
(
    code     bigint         NOT NULL UNIQUE PRIMARY KEY, -- L3_Product_Category_Code
    name     varchar(512)   NOT NULL                     -- L3_Product_Category_Name
);

--changeset vasiliy.sharpf:4
CREATE TABLE promo.products
(
    material_code        bigint         NOT NULL UNIQUE PRIMARY KEY,                    -- Material_No
    material_desc_rus    varchar(1024)  NOT NULL,                                       -- Material_Desc_RUS
    category_code        bigint         NOT NULL REFERENCES promo.categories ("code")   -- L3_Product_Category_Code
);

--changeset vasiliy.sharpf:5
CREATE TABLE promo.prices
(
    id                      bigint     NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    material_code           bigint     NOT NULL REFERENCES promo.products ("material_code") ON DELETE CASCADE,  -- Material No
    chain_id                int        NOT NULL REFERENCES promo.chains ("id") ON DELETE CASCADE,               -- primary key instead of name (Chain_name)
    regular_price_per_unit  decimal    NOT NULL                                                                 -- Regular price per unit
);

CREATE UNIQUE INDEX idx_prices_material_code_chain_id ON promo.prices (material_code, chain_id);

--changeset vasiliy.sharpf:6
CREATE TABLE promo.customers
(
    ship_code        bigint        NOT NULL UNIQUE PRIMARY KEY,                           -- CH3 Ship To Code
    ship_name        varchar(512)  NOT NULL,                                              -- CH3 Ship To Name
    chain_id         int           NOT NULL REFERENCES promo.chains ("id")                -- primary key instead of name (Chain_name)
);

--changeset vasiliy.sharpf:7
CREATE TABLE promo.actuals
(
    id                  bigint        NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date                date          NOT NULL,                                               -- Date
    material_code       bigint        NOT NULL REFERENCES promo.products ("material_code"),   -- Material No
    ship_code           bigint        NOT NULL REFERENCES promo.customers ("ship_code"),      -- CH3 Ship To Code
    quantity            int           NOT NULL,                                               -- Volume, units
    actual_sales_value  decimal       NOT NULL,                                               -- Actual Sales Value
    shipment_type       varchar(20)                                                           -- Признак промо
);

CREATE INDEX idx_actuals_material_code ON promo.actuals (material_code);






